# 라이브러리 로드 및 기본 세팅

In [1]:
!pip install catboost

Collecting catboost
  Downloading catboost-1.0.4-cp37-none-manylinux1_x86_64.whl (76.1 MB)
     |████████████████████████████████| 76.1 MB 1.2 MB/s
Requirement already satisfied: plotly in /usr/local/lib/python3.7/dist-packages (from catboost) (4.4.1)
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from catboost) (1.15.0)
Requirement already satisfied: pandas>=0.24.0 in /usr/local/lib/python3.7/dist-packages (from catboost) (1.1.5)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.7/dist-packages (from catboost) (3.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.7/dist-packages (from catboost) (1.4.1)
Requirement already satisfied: numpy>=1.16.0 in /usr/local/lib/python3.7/dist-packages (from catboost) (1.19.5)
Requirement already satisfied: graphviz in /usr/local/lib/python3.7/dist-packages (from catboost) (0.10.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->catboost) (2.8.2)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->catboost) (2018.9)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib->catboost) (3.0.6)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib->catboost) (0.11.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib->catboost) (1.3.2)
Requirement already satisfied: retrying>=1.3.3 in /usr/local/lib/python3.7/dist-packages (from plotly->catboost) (1.3.3)
Installing collected packages: catboost
Successfully installed catboost-1.0.4

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import pandas as pd
import numpy as np
from tqdm import tqdm
from catboost import CatBoostClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score, classification_report, precision_recall_curve

# 데이콘 점수

In [4]:
# 자체 점수 : 
# 제출 점수(제출 날짜) :

# 설정

In [5]:
# cat
# test_size = 0.1
# one_hot_max_size = 2
# random_state : 5(range(10, 60, 10))
# iterations = 1000
# early_stopping_rounds = 77
# 순서형 특성 수치형으로 지정(4개)
# 'person_attribute_a_a', 'person_attribute_b', 'person_prefer_e', 'contents_attribute_e'
# probability_threshold :

In [6]:
# 제거된 특성(7개)
# 'id',
# 'contents_open_dt',
# 'contents_rn',
# 'person_prefer_f',
# 'person_prefer_g',
# 'h_m_match_yn',
# 'h_s_match_yn'

# 데이터 불러오기

In [7]:
# train = pd.read_csv('../data/df_train.csv')
# test = pd.read_csv('../data/df_test.csv')
train = pd.read_csv('/content/drive/MyDrive/GitHub/Dacon/TP2(잡케어)/data/df_train.csv')
test = pd.read_csv('/content/drive/MyDrive/GitHub/Dacon/TP2(잡케어)/data/df_test.csv')

# 데이터 확인

In [8]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 501951 entries, 0 to 501950
Data columns (total 63 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   id                      501951 non-null  int64
 1   d_l_match_yn            501951 non-null  bool
 2   d_m_match_yn            501951 non-null  bool
 3   d_s_match_yn            501951 non-null  bool
 4   h_l_match_yn            501951 non-null  bool
 5   h_m_match_yn            501951 non-null  bool
 6   h_s_match_yn            501951 non-null  bool
 7   person_attribute_a      501951 non-null  int64
 8   person_attribute_a_1    501951 non-null  int64
 9   person_attribute_b      501951 non-null  int64
 10  person_prefer_c         501951 non-null  int64
 11  person_prefer_d_1       501951 non-null  int64
 12  person_prefer_d_2       501951 non-null  int64
 13  person_prefer_d_3       501951 non-null  int64
 14  person_prefer_e         501951 non-null  int64
 15  person_prefer_f         501951 non-null  int64
 16  person_prefer_g         501951 non-null  int64
 17  person_prefer_h_1       501951 non-null  int64
 18  person_prefer_h_2       501951 non-null  int64
 19  person_prefer_h_3       501951 non-null  int64
 20  contents_attribute_i    501951 non-null  int64
 21  contents_attribute_a    501951 non-null  int64
 22  contents_attribute_j_1  501951 non-null  int64
 23  contents_attribute_j    501951 non-null  int64
 24  contents_attribute_c    501951 non-null  int64
 25  contents_attribute_k    501951 non-null  int64
 26  contents_attribute_l    501951 non-null  int64
 27  contents_attribute_d    501951 non-null  int64
 28  contents_attribute_m    501951 non-null  int64
 29  contents_attribute_e    501951 non-null  int64
 30  contents_attribute_h    501951 non-null  int64
 31  person_rn               501951 non-null  int64
 32  contents_rn             501951 non-null  int64
 33  contents_open_dt        501951 non-null  object
 34  target                  501951 non-null  int64
 35  person_prefer_d_1_n     501951 non-null  int64
 36  person_prefer_d_1_s     501951 non-null  int64
 37  person_prefer_d_1_m     501951 non-null  int64
 38  person_prefer_d_1_l     501951 non-null  int64
 39  person_prefer_d_2_n     501951 non-null  int64
 40  person_prefer_d_2_s     501951 non-null  int64
 41  person_prefer_d_2_m     501951 non-null  int64
 42  person_prefer_d_2_l     501951 non-null  int64
 43  person_prefer_d_3_n     501951 non-null  int64
 44  person_prefer_d_3_s     501951 non-null  int64
 45  person_prefer_d_3_m     501951 non-null  int64
 46  person_prefer_d_3_l     501951 non-null  int64
 47  contents_attribute_d_n  501951 non-null  int64
 48  contents_attribute_d_s  501951 non-null  int64
 49  contents_attribute_d_m  501951 non-null  int64
 50  contents_attribute_d_l  501951 non-null  int64
 51  person_prefer_h_1_m     501951 non-null  int64
 52  person_prefer_h_1_l     501951 non-null  int64
 53  person_prefer_h_2_m     501951 non-null  int64
 54  person_prefer_h_2_l     501951 non-null  int64
 55  person_prefer_h_3_m     501951 non-null  int64
 56  person_prefer_h_3_l     501951 non-null  int64
 57  contents_attribute_h_m  501951 non-null  int64
 58  contents_attribute_h_l  501951 non-null  int64
 59  contents_attribute_l_n  501951 non-null  int64
 60  contents_attribute_l_s  501951 non-null  int64
 61  contents_attribute_l_m  501951 non-null  int64
 62  contents_attribute_l_l  501951 non-null  int64
dtypes: bool(6), int64(56), object(1)
memory usage: 221.2+ MB

In [9]:
train.head()

   id  d_l_match_yn  ...  contents_attribute_l_m  contents_attribute_l_l
0   0          True  ...                    1605                    2016
1   1         False  ...                    1605                    2016
2   2         False  ...                    1572                    2016
3   3         False  ...                    1605                    2016
4   4          True  ...                    1605                    2016

[5 rows x 63 columns]

In [10]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46404 entries, 0 to 46403
Data columns (total 62 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      46404 non-null  int64
 1   d_l_match_yn            46404 non-null  bool
 2   d_m_match_yn            46404 non-null  bool
 3   d_s_match_yn            46404 non-null  bool
 4   h_l_match_yn            46404 non-null  bool
 5   h_m_match_yn            46404 non-null  bool
 6   h_s_match_yn            46404 non-null  bool
 7   person_attribute_a      46404 non-null  int64
 8   person_attribute_a_1    46404 non-null  int64
 9   person_attribute_b      46404 non-null  int64
 10  person_prefer_c         46404 non-null  int64
 11  person_prefer_d_1       46404 non-null  int64
 12  person_prefer_d_2       46404 non-null  int64
 13  person_prefer_d_3       46404 non-null  int64
 14  person_prefer_e         46404 non-null  int64
 15  person_prefer_f         46404 non-null  int64
 16  person_prefer_g         46404 non-null  int64
 17  person_prefer_h_1       46404 non-null  int64
 18  person_prefer_h_2       46404 non-null  int64
 19  person_prefer_h_3       46404 non-null  int64
 20  contents_attribute_i    46404 non-null  int64
 21  contents_attribute_a    46404 non-null  int64
 22  contents_attribute_j_1  46404 non-null  int64
 23  contents_attribute_j    46404 non-null  int64
 24  contents_attribute_c    46404 non-null  int64
 25  contents_attribute_k    46404 non-null  int64
 26  contents_attribute_l    46404 non-null  int64
 27  contents_attribute_d    46404 non-null  int64
 28  contents_attribute_m    46404 non-null  int64
 29  contents_attribute_e    46404 non-null  int64
 30  contents_attribute_h    46404 non-null  int64
 31  person_rn               46404 non-null  int64
 32  contents_rn             46404 non-null  int64
 33  contents_open_dt        46404 non-null  object
 34  person_prefer_d_1_n     46404 non-null  int64
 35  person_prefer_d_1_s     46404 non-null  int64
 36  person_prefer_d_1_m     46404 non-null  int64
 37  person_prefer_d_1_l     46404 non-null  int64
 38  person_prefer_d_2_n     46404 non-null  int64
 39  person_prefer_d_2_s     46404 non-null  int64
 40  person_prefer_d_2_m     46404 non-null  int64
 41  person_prefer_d_2_l     46404 non-null  int64
 42  person_prefer_d_3_n     46404 non-null  int64
 43  person_prefer_d_3_s     46404 non-null  int64
 44  person_prefer_d_3_m     46404 non-null  int64
 45  person_prefer_d_3_l     46404 non-null  int64
 46  contents_attribute_d_n  46404 non-null  int64
 47  contents_attribute_d_s  46404 non-null  int64
 48  contents_attribute_d_m  46404 non-null  int64
 49  contents_attribute_d_l  46404 non-null  int64
 50  person_prefer_h_1_m     46404 non-null  int64
 51  person_prefer_h_1_l     46404 non-null  int64
 52  person_prefer_h_2_m     46404 non-null  int64
 53  person_prefer_h_2_l     46404 non-null  int64
 54  person_prefer_h_3_m     46404 non-null  int64
 55  person_prefer_h_3_l     46404 non-null  int64
 56  contents_attribute_h_m  46404 non-null  int64
 57  contents_attribute_h_l  46404 non-null  int64
 58  contents_attribute_l_n  46404 non-null  int64
 59  contents_attribute_l_s  46404 non-null  int64
 60  contents_attribute_l_m  46404 non-null  int64
 61  contents_attribute_l_l  46404 non-null  int64
dtypes: bool(6), int64(55), object(1)
memory usage: 20.1+ MB

In [11]:
test.head()

   id  d_l_match_yn  ...  contents_attribute_l_m  contents_attribute_l_l
0   0          True  ...                    1021                    2010
1   1         False  ...                    1605                    2016
2   2          True  ...                    1810                    2020
3   3          True  ...                      99                    2006
4   4          True  ...                     954                    2009

[5 rows x 62 columns]

# 필요 데이터 추출

## 훈련에 의미가 적은 열 제거

In [12]:
# 제거된 특성(7개)
# 'id',
# 'contents_open_dt',
# 'contents_rn',
# 'person_prefer_f',
# 'person_prefer_g',
# 'h_m_match_yn',
# 'h_s_match_yn'

In [13]:
# 삭제할 특성
pop_col = ['id',
'contents_open_dt',
'contents_rn',
'person_prefer_f',
'person_prefer_g',
'h_m_match_yn',
'h_s_match_yn']
len(pop_col)

7

In [14]:
train = train.drop(pop_col, axis=1) 
test = test.drop(pop_col, axis=1)

In [15]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 501951 entries, 0 to 501950
Data columns (total 56 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   d_l_match_yn            501951 non-null  bool
 1   d_m_match_yn            501951 non-null  bool
 2   d_s_match_yn            501951 non-null  bool
 3   h_l_match_yn            501951 non-null  bool
 4   person_attribute_a      501951 non-null  int64
 5   person_attribute_a_1    501951 non-null  int64
 6   person_attribute_b      501951 non-null  int64
 7   person_prefer_c         501951 non-null  int64
 8   person_prefer_d_1       501951 non-null  int64
 9   person_prefer_d_2       501951 non-null  int64
 10  person_prefer_d_3       501951 non-null  int64
 11  person_prefer_e         501951 non-null  int64
 12  person_prefer_h_1       501951 non-null  int64
 13  person_prefer_h_2       501951 non-null  int64
 14  person_prefer_h_3       501951 non-null  int64
 15  contents_attribute_i    501951 non-null  int64
 16  contents_attribute_a    501951 non-null  int64
 17  contents_attribute_j_1  501951 non-null  int64
 18  contents_attribute_j    501951 non-null  int64
 19  contents_attribute_c    501951 non-null  int64
 20  contents_attribute_k    501951 non-null  int64
 21  contents_attribute_l    501951 non-null  int64
 22  contents_attribute_d    501951 non-null  int64
 23  contents_attribute_m    501951 non-null  int64
 24  contents_attribute_e    501951 non-null  int64
 25  contents_attribute_h    501951 non-null  int64
 26  person_rn               501951 non-null  int64
 27  target                  501951 non-null  int64
 28  person_prefer_d_1_n     501951 non-null  int64
 29  person_prefer_d_1_s     501951 non-null  int64
 30  person_prefer_d_1_m     501951 non-null  int64
 31  person_prefer_d_1_l     501951 non-null  int64
 32  person_prefer_d_2_n     501951 non-null  int64
 33  person_prefer_d_2_s     501951 non-null  int64
 34  person_prefer_d_2_m     501951 non-null  int64
 35  person_prefer_d_2_l     501951 non-null  int64
 36  person_prefer_d_3_n     501951 non-null  int64
 37  person_prefer_d_3_s     501951 non-null  int64
 38  person_prefer_d_3_m     501951 non-null  int64
 39  person_prefer_d_3_l     501951 non-null  int64
 40  contents_attribute_d_n  501951 non-null  int64
 41  contents_attribute_d_s  501951 non-null  int64
 42  contents_attribute_d_m  501951 non-null  int64
 43  contents_attribute_d_l  501951 non-null  int64
 44  person_prefer_h_1_m     501951 non-null  int64
 45  person_prefer_h_1_l     501951 non-null  int64
 46  person_prefer_h_2_m     501951 non-null  int64
 47  person_prefer_h_2_l     501951 non-null  int64
 48  person_prefer_h_3_m     501951 non-null  int64
 49  person_prefer_h_3_l     501951 non-null  int64
 50  contents_attribute_h_m  501951 non-null  int64
 51  contents_attribute_h_l  501951 non-null  int64
 52  contents_attribute_l_n  501951 non-null  int64
 53  contents_attribute_l_s  501951 non-null  int64
 54  contents_attribute_l_m  501951 non-null  int64
 55  contents_attribute_l_l  501951 non-null  int64
dtypes: bool(4), int64(52)
memory usage: 201.1 MB

In [16]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46404 entries, 0 to 46403
Data columns (total 55 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   d_l_match_yn            46404 non-null  bool
 1   d_m_match_yn            46404 non-null  bool
 2   d_s_match_yn            46404 non-null  bool
 3   h_l_match_yn            46404 non-null  bool
 4   person_attribute_a      46404 non-null  int64
 5   person_attribute_a_1    46404 non-null  int64
 6   person_attribute_b      46404 non-null  int64
 7   person_prefer_c         46404 non-null  int64
 8   person_prefer_d_1       46404 non-null  int64
 9   person_prefer_d_2       46404 non-null  int64
 10  person_prefer_d_3       46404 non-null  int64
 11  person_prefer_e         46404 non-null  int64
 12  person_prefer_h_1       46404 non-null  int64
 13  person_prefer_h_2       46404 non-null  int64
 14  person_prefer_h_3       46404 non-null  int64
 15  contents_attribute_i    46404 non-null  int64
 16  contents_attribute_a    46404 non-null  int64
 17  contents_attribute_j_1  46404 non-null  int64
 18  contents_attribute_j    46404 non-null  int64
 19  contents_attribute_c    46404 non-null  int64
 20  contents_attribute_k    46404 non-null  int64
 21  contents_attribute_l    46404 non-null  int64
 22  contents_attribute_d    46404 non-null  int64
 23  contents_attribute_m    46404 non-null  int64
 24  contents_attribute_e    46404 non-null  int64
 25  contents_attribute_h    46404 non-null  int64
 26  person_rn               46404 non-null  int64
 27  person_prefer_d_1_n     46404 non-null  int64
 28  person_prefer_d_1_s     46404 non-null  int64
 29  person_prefer_d_1_m     46404 non-null  int64
 30  person_prefer_d_1_l     46404 non-null  int64
 31  person_prefer_d_2_n     46404 non-null  int64
 32  person_prefer_d_2_s     46404 non-null  int64
 33  person_prefer_d_2_m     46404 non-null  int64
 34  person_prefer_d_2_l     46404 non-null  int64
 35  person_prefer_d_3_n     46404 non-null  int64
 36  person_prefer_d_3_s     46404 non-null  int64
 37  person_prefer_d_3_m     46404 non-null  int64
 38  person_prefer_d_3_l     46404 non-null  int64
 39  contents_attribute_d_n  46404 non-null  int64
 40  contents_attribute_d_s  46404 non-null  int64
 41  contents_attribute_d_m  46404 non-null  int64
 42  contents_attribute_d_l  46404 non-null  int64
 43  person_prefer_h_1_m     46404 non-null  int64
 44  person_prefer_h_1_l     46404 non-null  int64
 45  person_prefer_h_2_m     46404 non-null  int64
 46  person_prefer_h_2_l     46404 non-null  int64
 47  person_prefer_h_3_m     46404 non-null  int64
 48  person_prefer_h_3_l     46404 non-null  int64
 49  contents_attribute_h_m  46404 non-null  int64
 50  contents_attribute_h_l  46404 non-null  int64
 51  contents_attribute_l_n  46404 non-null  int64
 52  contents_attribute_l_s  46404 non-null  int64
 53  contents_attribute_l_m  46404 non-null  int64
 54  contents_attribute_l_l  46404 non-null  int64
dtypes: bool(4), int64(51)
memory usage: 18.2 MB

## 카테고리형 특성 원핫인코딩시 컬럼 명 겹치는 문제 해결위해 특성명 변경

In [17]:
# 카테고리형 특성 원핫인코딩시 컬럼 명 겹치는 문제 해결위해 특성명 변경
train = train.rename(columns={'person_attribute_a_1':'person_attribute_a_a'})
train = train.rename(columns={'contents_attribute_j_1':'contents_attribute_j_a'})
train.head()

   d_l_match_yn  d_m_match_yn  ...  contents_attribute_l_m  contents_attribute_l_l
0          True          True  ...                    1605                    2016
1         False         False  ...                    1605                    2016
2         False         False  ...                    1572                    2016
3         False         False  ...                    1605                    2016
4          True          True  ...                    1605                    2016

[5 rows x 56 columns]

In [18]:
# 카테고리형 특성 원핫인코딩시 컬럼 명 겹치는 문제 해결위해 특성명 변경
test = test.rename(columns={'person_attribute_a_1':'person_attribute_a_a'})
test = test.rename(columns={'contents_attribute_j_1':'contents_attribute_j_a'})
test.head()

   d_l_match_yn  d_m_match_yn  ...  contents_attribute_l_m  contents_attribute_l_l
0          True         False  ...                    1021                    2010
1         False         False  ...                    1605                    2016
2          True         False  ...                    1810                    2020
3          True         False  ...                      99                    2006
4          True         False  ...                     954                    2009

[5 rows x 55 columns]

## 카테고리형 특성으로 지정할 특성

In [19]:
# 원본 데이터에서 순서형 특성
# 'person_attribute_a_a', 'person_attribute_b', 'person_prefer_e', 'contents_attribute_e'

In [20]:
# 순서형 특성 수치형으로 지정 : ⭕
# 'person_attribute_a_a', 'person_attribute_b', 'person_prefer_e', 'contents_attribute_e'

In [21]:
cat_f = train.columns.tolist()
numeric_cat = ['person_attribute_a_a', 'person_attribute_b', 'person_prefer_e', 'contents_attribute_e']
for col in numeric_cat:
  cat_f.remove(col)
cat_f.remove('target')

In [22]:
# 56 - 5 = 51개
len(cat_f)

51

# train, test 셋 준비

In [23]:
train.shape

(501951, 56)

In [24]:
X = train.drop(['target'], axis=1)
X.shape

(501951, 55)

In [25]:
y = train[['target']]
y.shape

(501951, 1)

# 모델 훈련/예측

In [28]:
all_thr_df = pd.DataFrame()
all_score_df = pd.DataFrame()
all_pred_proba_df = pd.DataFrame()

for test_size in [0.1, 0.2, 0.3, 0.4, 0.5]:
  score_df = pd.DataFrame(index=['thr_전', 'thr_후'])
  pred_proba_df = pd.DataFrame()
  thr_df = pd.DataFrame()
  for random_state in tqdm(range(10, 60, 10)):
    temp_score_list =[]
    # 데이터 셋 나누기
    X_train, X_val, y_train, y_val = train_test_split(X, y, random_state=random_state, test_size=test_size,
                                                      shuffle=True, stratify=y)
    # 모델 생성
    cat = CatBoostClassifier(random_state=0, task_type='GPU', iterations=1000, early_stopping_rounds=77,
                          cat_features=cat_f, eval_metric='F1', one_hot_max_size=2)
    # 모델 훈련
    cat.fit(X_train, y_train, eval_set=(X_val, y_val), verbose=100)
    
    # 기본 평가
    val_pred = cat.predict(X_val)
    f1_score_raw = f1_score(y_val, val_pred)
    temp_score_list.append(f1_score_raw)

    # precision, recall, threshold 값 계산
    val_pred_proba = cat.predict_proba(X_val)
    precisions, recalls, thresholds = precision_recall_curve(y_val, val_pred_proba[:,1])
    threshold_boundary = thresholds.shape[0]

    # 최고 F1 값을 갖는 threshold 값 구하기
    pre = precisions[:threshold_boundary]
    re = recalls[:threshold_boundary]
    f1 = 2 * pre * re / (pre + re)
    optimal_idx = np.argmax(f1)
    optimal_threshold = thresholds[optimal_idx]
    thr_df[f'{random_state}'] = [optimal_threshold]

    # 구한 threshold값으로 제한해서 예측
    # 1의 예측값만 불러와도 되므로 [:,1]사용
    val_pred_th =  (val_pred_proba[:,1] >= optimal_threshold)
    val_pred_th = val_pred_th.astype(int)

    # threshold로 제한한 예측 평가
    f1_score_mod = f1_score(y_val, val_pred_th)
    temp_score_list.append(f1_score_mod)
    score_df[f'{random_state}'] = temp_score_list

    print("===============================================")
    print(f"test_size : {test_size}")
    print(f"random_state : {random_state}")
    print("threshold 적용 전 f1 score :", f1_score_raw)
    print("threshold 적용 후 f1 score :", f1_score_mod)
    print("===============================================")
    print()

    # test 셋 예측
    pred_proba = cat.predict_proba(test)
    pred_proba_df[f'{random_state}'] = pred_proba[:,1]
  
  #결과 종합
  all_thr_df = pd.concat([all_thr_df, thr_df])
  all_score_df = pd.concat([all_score_df, score_df])
  all_pred_proba_df = pd.concat([all_pred_proba_df, pred_proba_df], axis=1)

# about 42m

  0%|          | 0/5 [00:00<?, ?it/s]

Learning rate set to 0.04235
0:	learn: 0.6306710	test: 0.6331043	best: 0.6331043 (0)	total: 262ms	remaining: 4m 21s
100:	learn: 0.6499799	test: 0.6630939	best: 0.6633598 (98)	total: 16.2s	remaining: 2m 24s
200:	learn: 0.6602050	test: 0.6802622	best: 0.6802622 (200)	total: 32.4s	remaining: 2m 8s
300:	learn: 0.6654267	test: 0.6827868	best: 0.6827875 (266)	total: 48.5s	remaining: 1m 52s
400:	learn: 0.6695283	test: 0.6838343	best: 0.6840719 (393)	total: 1m 4s	remaining: 1m 36s
500:	learn: 0.6721068	test: 0.6859740	best: 0.6861131 (499)	total: 1m 20s	remaining: 1m 20s
bestTest = 0.6861694039
bestIteration = 518
Shrink model to first 519 iterations.
===============================================
test_size : 0.1
random_state : 10
threshold 적용 전 f1 score : 0.686169403892944
threshold 적용 후 f1 score : 0.7153941302147755
===============================================

 20%|██        | 1/5 [02:05<08:21, 125.43s/it]

Learning rate set to 0.04235
0:	learn: 0.6241250	test: 0.6281235	best: 0.6281235 (0)	total: 218ms	remaining: 3m 37s
100:	learn: 0.6515090	test: 0.6635505	best: 0.6635505 (100)	total: 16.4s	remaining: 2m 25s
200:	learn: 0.6615456	test: 0.6787594	best: 0.6787594 (200)	total: 32.7s	remaining: 2m 9s
300:	learn: 0.6667060	test: 0.6825448	best: 0.6826314 (294)	total: 48.5s	remaining: 1m 52s
400:	learn: 0.6700286	test: 0.6830176	best: 0.6832465 (383)	total: 1m 4s	remaining: 1m 36s
500:	learn: 0.6725884	test: 0.6839997	best: 0.6841794 (498)	total: 1m 20s	remaining: 1m 20s
600:	learn: 0.6747834	test: 0.6847947	best: 0.6849514 (577)	total: 1m 36s	remaining: 1m 3s
bestTest = 0.6849514192
bestIteration = 577
Shrink model to first 578 iterations.
===============================================
test_size : 0.1
random_state : 20
threshold 적용 전 f1 score : 0.6849514191722134
threshold 적용 후 f1 score : 0.7167734251778415
===============================================

 40%|████      | 2/5 [04:19<06:31, 130.66s/it]

Learning rate set to 0.04235
0:	learn: 0.6339293	test: 0.6377636	best: 0.6377636 (0)	total: 221ms	remaining: 3m 40s
100:	learn: 0.6510515	test: 0.6641342	best: 0.6641342 (100)	total: 16.5s	remaining: 2m 26s
200:	learn: 0.6618358	test: 0.6795036	best: 0.6797509 (196)	total: 33.1s	remaining: 2m 11s
300:	learn: 0.6671323	test: 0.6823512	best: 0.6829962 (288)	total: 49s	remaining: 1m 53s
400:	learn: 0.6705489	test: 0.6846850	best: 0.6847589 (382)	total: 1m 5s	remaining: 1m 37s
500:	learn: 0.6731859	test: 0.6846775	best: 0.6853756 (478)	total: 1m 21s	remaining: 1m 20s
bestTest = 0.6853755989
bestIteration = 478
Shrink model to first 479 iterations.
===============================================
test_size : 0.1
random_state : 30
threshold 적용 전 f1 score : 0.6853755988562555
threshold 적용 후 f1 score : 0.713986213906801
===============================================

 60%|██████    | 3/5 [06:18<04:10, 125.34s/it]

Learning rate set to 0.04235
0:	learn: 0.5969520	test: 0.6040401	best: 0.6040401 (0)	total: 221ms	remaining: 3m 41s
100:	learn: 0.6502860	test: 0.6658381	best: 0.6660900 (98)	total: 16.1s	remaining: 2m 23s
200:	learn: 0.6609394	test: 0.6807753	best: 0.6808085 (198)	total: 32s	remaining: 2m 7s
300:	learn: 0.6661915	test: 0.6823944	best: 0.6823944 (300)	total: 48.3s	remaining: 1m 52s
400:	learn: 0.6701058	test: 0.6827903	best: 0.6830080 (395)	total: 1m 4s	remaining: 1m 36s
500:	learn: 0.6730384	test: 0.6836851	best: 0.6840078 (483)	total: 1m 20s	remaining: 1m 19s
bestTest = 0.6840078168
bestIteration = 483
Shrink model to first 484 iterations.
===============================================
test_size : 0.1
random_state : 40
threshold 적용 전 f1 score : 0.6840078167985277
threshold 적용 후 f1 score : 0.7124230293091528
===============================================

 80%|████████  | 4/5 [08:17<02:02, 122.92s/it]

Learning rate set to 0.04235
0:	learn: 0.6276374	test: 0.6318710	best: 0.6318710 (0)	total: 236ms	remaining: 3m 55s
100:	learn: 0.6519852	test: 0.6667921	best: 0.6674684 (94)	total: 16.3s	remaining: 2m 24s
200:	learn: 0.6617995	test: 0.6794692	best: 0.6799620 (192)	total: 32.6s	remaining: 2m 9s
300:	learn: 0.6670800	test: 0.6828974	best: 0.6829994 (287)	total: 48.7s	remaining: 1m 53s
400:	learn: 0.6705891	test: 0.6839109	best: 0.6843651 (386)	total: 1m 5s	remaining: 1m 37s
bestTest = 0.6843651109
bestIteration = 386
Shrink model to first 387 iterations.
===============================================
test_size : 0.1
random_state : 50
threshold 적용 전 f1 score : 0.6843651109468857
threshold 적용 후 f1 score : 0.713623545428025
===============================================

100%|██████████| 5/5 [10:01<00:00, 120.37s/it]
  0%|          | 0/5 [00:00<?, ?it/s]

Learning rate set to 0.042777
0:	learn: 0.6217416	test: 0.6236252	best: 0.6236252 (0)	total: 201ms	remaining: 3m 20s
100:	learn: 0.6498959	test: 0.6629596	best: 0.6629596 (100)	total: 14.4s	remaining: 2m 7s
200:	learn: 0.6597657	test: 0.6770811	best: 0.6776624 (190)	total: 28.6s	remaining: 1m 53s
300:	learn: 0.6647980	test: 0.6801818	best: 0.6804227 (297)	total: 43.1s	remaining: 1m 40s
400:	learn: 0.6682529	test: 0.6814491	best: 0.6816838 (377)	total: 57.2s	remaining: 1m 25s
500:	learn: 0.6708827	test: 0.6814833	best: 0.6820932 (424)	total: 1m 11s	remaining: 1m 11s
bestTest = 0.6820932041
bestIteration = 424
Shrink model to first 425 iterations.
===============================================
test_size : 0.2
random_state : 10
threshold 적용 전 f1 score : 0.6820932041044704
threshold 적용 후 f1 score : 0.7116416953769731
===============================================

 20%|██        | 1/5 [01:42<06:51, 102.94s/it]

Learning rate set to 0.042777
0:	learn: 0.6304554	test: 0.6354836	best: 0.6354836 (0)	total: 199ms	remaining: 3m 19s
100:	learn: 0.6508590	test: 0.6642193	best: 0.6646652 (98)	total: 14.4s	remaining: 2m 8s
200:	learn: 0.6610973	test: 0.6784504	best: 0.6785757 (199)	total: 28.7s	remaining: 1m 54s
300:	learn: 0.6660665	test: 0.6802123	best: 0.6806278 (297)	total: 43.4s	remaining: 1m 40s
400:	learn: 0.6695571	test: 0.6832182	best: 0.6832182 (400)	total: 57.5s	remaining: 1m 25s
bestTest = 0.6833393307
bestIteration = 410
Shrink model to first 411 iterations.
===============================================
test_size : 0.2
random_state : 20
threshold 적용 전 f1 score : 0.6833393306944944
threshold 적용 후 f1 score : 0.7115253105170248
===============================================

 40%|████      | 2/5 [03:23<05:04, 101.44s/it]

Learning rate set to 0.042777
0:	learn: 0.6212636	test: 0.6261839	best: 0.6261839 (0)	total: 211ms	remaining: 3m 31s
100:	learn: 0.6494500	test: 0.6659754	best: 0.6659754 (100)	total: 14.6s	remaining: 2m 10s
200:	learn: 0.6590278	test: 0.6800185	best: 0.6800207 (197)	total: 29.2s	remaining: 1m 55s
300:	learn: 0.6641499	test: 0.6829250	best: 0.6831337 (296)	total: 43.5s	remaining: 1m 41s
400:	learn: 0.6681002	test: 0.6833910	best: 0.6835689 (397)	total: 57.9s	remaining: 1m 26s
500:	learn: 0.6709974	test: 0.6842643	best: 0.6845955 (478)	total: 1m 12s	remaining: 1m 11s
600:	learn: 0.6727268	test: 0.6847267	best: 0.6850203 (585)	total: 1m 26s	remaining: 57.2s
700:	learn: 0.6744271	test: 0.6851108	best: 0.6854630 (650)	total: 1m 39s	remaining: 42.5s
bestTest = 0.6854630403
bestIteration = 650
Shrink model to first 651 iterations.
===============================================
test_size : 0.2
random_state : 30
threshold 적용 전 f1 score : 0.685463040340348
threshold 적용 후 f1 score : 0.7125750936892848
===============================================

 60%|██████    | 3/5 [05:40<03:55, 117.58s/it]

Learning rate set to 0.042777
0:	learn: 0.6069466	test: 0.6065823	best: 0.6065823 (0)	total: 203ms	remaining: 3m 22s
100:	learn: 0.6479396	test: 0.6565357	best: 0.6579050 (86)	total: 14.5s	remaining: 2m 9s
200:	learn: 0.6595799	test: 0.6750235	best: 0.6750784 (199)	total: 28.9s	remaining: 1m 54s
300:	learn: 0.6646566	test: 0.6759352	best: 0.6766869 (243)	total: 43.6s	remaining: 1m 41s
400:	learn: 0.6678678	test: 0.6781633	best: 0.6781633 (400)	total: 58.2s	remaining: 1m 26s
500:	learn: 0.6706660	test: 0.6788795	best: 0.6788994 (482)	total: 1m 12s	remaining: 1m 12s
600:	learn: 0.6728457	test: 0.6796344	best: 0.6797329 (596)	total: 1m 26s	remaining: 57.4s
700:	learn: 0.6743882	test: 0.6801088	best: 0.6802226 (693)	total: 1m 40s	remaining: 42.7s
800:	learn: 0.6760696	test: 0.6801338	best: 0.6803801 (738)	total: 1m 53s	remaining: 28.2s
bestTest = 0.6803801136
bestIteration = 738
Shrink model to first 739 iterations.
===============================================
test_size : 0.2
random_state : 40
threshold 적용 전 f1 score : 0.6803801135705181
threshold 적용 후 f1 score : 0.7140023420882824
===============================================

 80%|████████  | 4/5 [08:10<02:10, 130.55s/it]

Learning rate set to 0.042777
0:	learn: 0.6285014	test: 0.6286496	best: 0.6286496 (0)	total: 229ms	remaining: 3m 49s
100:	learn: 0.6506829	test: 0.6630595	best: 0.6633145 (99)	total: 14.2s	remaining: 2m 6s
200:	learn: 0.6604046	test: 0.6760265	best: 0.6760265 (200)	total: 28.6s	remaining: 1m 53s
300:	learn: 0.6652189	test: 0.6795781	best: 0.6796721 (297)	total: 43.1s	remaining: 1m 40s
400:	learn: 0.6683448	test: 0.6793911	best: 0.6799181 (333)	total: 57.7s	remaining: 1m 26s
bestTest = 0.6799181415
bestIteration = 333
Shrink model to first 334 iterations.
===============================================
test_size : 0.2
random_state : 50
threshold 적용 전 f1 score : 0.6799181415090765
threshold 적용 후 f1 score : 0.7099491442696771
===============================================

100%|██████████| 5/5 [09:39<00:00, 115.96s/it]
  0%|          | 0/5 [00:00<?, ?it/s]

Learning rate set to 0.043265
0:	learn: 0.6090855	test: 0.6068882	best: 0.6068882 (0)	total: 182ms	remaining: 3m 2s
100:	learn: 0.6472159	test: 0.6601392	best: 0.6601392 (100)	total: 12.7s	remaining: 1m 52s
200:	learn: 0.6575996	test: 0.6733853	best: 0.6733853 (200)	total: 25.5s	remaining: 1m 41s
300:	learn: 0.6632651	test: 0.6751627	best: 0.6755282 (264)	total: 38.3s	remaining: 1m 28s
400:	learn: 0.6669122	test: 0.6761187	best: 0.6763990 (390)	total: 51s	remaining: 1m 16s
bestTest = 0.6765915843
bestIteration = 440
Shrink model to first 441 iterations.
===============================================
test_size : 0.3
random_state : 10
threshold 적용 전 f1 score : 0.676591584346987
threshold 적용 후 f1 score : 0.7092478343878695
===============================================

 20%|██        | 1/5 [01:38<06:35, 98.78s/it]

Learning rate set to 0.043265
0:	learn: 0.6328227	test: 0.6387079	best: 0.6387079 (0)	total: 196ms	remaining: 3m 15s
100:	learn: 0.6498024	test: 0.6652257	best: 0.6652257 (100)	total: 12.7s	remaining: 1m 53s
200:	learn: 0.6587465	test: 0.6757572	best: 0.6759722 (179)	total: 25.4s	remaining: 1m 40s
300:	learn: 0.6632785	test: 0.6788114	best: 0.6792669 (255)	total: 37.9s	remaining: 1m 28s
400:	learn: 0.6669159	test: 0.6791716	best: 0.6795454 (328)	total: 50.8s	remaining: 1m 15s
bestTest = 0.6795453834
bestIteration = 328
Shrink model to first 329 iterations.
===============================================
test_size : 0.3
random_state : 20
threshold 적용 전 f1 score : 0.6795453833870816
threshold 적용 후 f1 score : 0.707529394427427
===============================================

 40%|████      | 2/5 [03:01<04:28, 89.56s/it]

Learning rate set to 0.043265
0:	learn: 0.6214672	test: 0.6287570	best: 0.6287570 (0)	total: 235ms	remaining: 3m 54s
100:	learn: 0.6465440	test: 0.6581475	best: 0.6582036 (97)	total: 12.6s	remaining: 1m 52s
200:	learn: 0.6576458	test: 0.6753801	best: 0.6753849 (199)	total: 25.4s	remaining: 1m 41s
300:	learn: 0.6627889	test: 0.6785474	best: 0.6787727 (268)	total: 38s	remaining: 1m 28s
400:	learn: 0.6663591	test: 0.6801278	best: 0.6801579 (398)	total: 50.6s	remaining: 1m 15s
bestTest = 0.6802465188
bestIteration = 408
Shrink model to first 409 iterations.
===============================================
test_size : 0.3
random_state : 30
threshold 적용 전 f1 score : 0.6802465188306029
threshold 적용 후 f1 score : 0.7079893915025509
===============================================

 60%|██████    | 3/5 [04:36<03:03, 91.65s/it]

Learning rate set to 0.043265
0:	learn: 0.6193929	test: 0.6271932	best: 0.6271932 (0)	total: 192ms	remaining: 3m 11s
100:	learn: 0.6483411	test: 0.6660577	best: 0.6660577 (100)	total: 12.6s	remaining: 1m 52s
200:	learn: 0.6571222	test: 0.6779600	best: 0.6779600 (200)	total: 25.4s	remaining: 1m 40s
300:	learn: 0.6618121	test: 0.6793257	best: 0.6798655 (276)	total: 38.2s	remaining: 1m 28s
bestTest = 0.6798654792
bestIteration = 276
Shrink model to first 277 iterations.
===============================================
test_size : 0.3
random_state : 40
threshold 적용 전 f1 score : 0.6798654792302422
threshold 적용 후 f1 score : 0.7059702116103695
===============================================

 80%|████████  | 4/5 [05:51<01:25, 85.37s/it]

Learning rate set to 0.043265
0:	learn: 0.6329333	test: 0.6377647	best: 0.6377647 (0)	total: 186ms	remaining: 3m 5s
100:	learn: 0.6482293	test: 0.6617934	best: 0.6617934 (100)	total: 13s	remaining: 1m 55s
200:	learn: 0.6577615	test: 0.6733825	best: 0.6736621 (192)	total: 25.5s	remaining: 1m 41s
300:	learn: 0.6623291	test: 0.6763237	best: 0.6767307 (296)	total: 38.1s	remaining: 1m 28s
400:	learn: 0.6655184	test: 0.6775525	best: 0.6778906 (376)	total: 51.1s	remaining: 1m 16s
500:	learn: 0.6682347	test: 0.6786762	best: 0.6788115 (497)	total: 1m 3s	remaining: 1m 3s
bestTest = 0.6788114991
bestIteration = 497
Shrink model to first 498 iterations.
===============================================
test_size : 0.3
random_state : 50
threshold 적용 전 f1 score : 0.67881149908279
threshold 적용 후 f1 score : 0.7105703050789894
===============================================

100%|██████████| 5/5 [07:38<00:00, 91.76s/it]
  0%|          | 0/5 [00:00<?, ?it/s]

Learning rate set to 0.043835
0:	learn: 0.6243251	test: 0.6262777	best: 0.6262777 (0)	total: 172ms	remaining: 2m 51s
100:	learn: 0.6481600	test: 0.6574753	best: 0.6574753 (100)	total: 11.2s	remaining: 1m 39s
200:	learn: 0.6563909	test: 0.6683607	best: 0.6684575 (199)	total: 22.2s	remaining: 1m 28s
300:	learn: 0.6615895	test: 0.6713284	best: 0.6713685 (298)	total: 33.5s	remaining: 1m 17s
bestTest = 0.6714393653
bestIteration = 302
Shrink model to first 303 iterations.
===============================================
test_size : 0.4
random_state : 10
threshold 적용 전 f1 score : 0.6714393653192293
threshold 적용 후 f1 score : 0.7036900325991086
===============================================

 20%|██        | 1/5 [01:15<05:01, 75.44s/it]

Learning rate set to 0.043835
0:	learn: 0.6230339	test: 0.6294736	best: 0.6294736 (0)	total: 171ms	remaining: 2m 51s
100:	learn: 0.6480599	test: 0.6608155	best: 0.6609135 (97)	total: 11.2s	remaining: 1m 39s
200:	learn: 0.6562287	test: 0.6700278	best: 0.6701636 (199)	total: 22.3s	remaining: 1m 28s
300:	learn: 0.6616239	test: 0.6731814	best: 0.6733391 (274)	total: 33.4s	remaining: 1m 17s
400:	learn: 0.6650302	test: 0.6734880	best: 0.6741406 (367)	total: 44.7s	remaining: 1m 6s
bestTest = 0.6741406493
bestIteration = 367
Shrink model to first 368 iterations.
===============================================
test_size : 0.4
random_state : 20
threshold 적용 전 f1 score : 0.6741406493396146
threshold 적용 후 f1 score : 0.705402811405189
===============================================

 40%|████      | 2/5 [02:39<04:01, 80.41s/it]

Learning rate set to 0.043835
100:	learn: 0.6466286	test: 0.6589404	best: 0.6591021 (99)	total: 11.2s	remaining: 1m 40s
200:	learn: 0.6562307	test: 0.6715475	best: 0.6715507 (199)	total: 22.5s	remaining: 1m 29s
300:	learn: 0.6608863	test: 0.6747670	best: 0.6747757 (299)	total: 33.8s	remaining: 1m 18s
400:	learn: 0.6645683	test: 0.6746295	best: 0.6753196 (374)	total: 44.8s	remaining: 1m 6s
bestTest = 0.6753195544
bestIteration = 374
Shrink model to first 375 iterations.
===============================================
test_size : 0.4
random_state : 30
threshold 적용 전 f1 score : 0.6753195544310453
threshold 적용 후 f1 score : 0.7045121006512591
===============================================

 60%|██████    | 3/5 [04:03<02:44, 82.35s/it]

Learning rate set to 0.043835
0:	learn: 0.6219241	test: 0.6206352	best: 0.6206352 (0)	total: 164ms	remaining: 2m 43s
100:	learn: 0.6479874	test: 0.6611923	best: 0.6612435 (99)	total: 11.2s	remaining: 1m 39s
200:	learn: 0.6557511	test: 0.6702612	best: 0.6707926 (190)	total: 22.1s	remaining: 1m 27s
300:	learn: 0.6606043	test: 0.6734966	best: 0.6738103 (284)	total: 33.4s	remaining: 1m 17s
400:	learn: 0.6643780	test: 0.6748397	best: 0.6750259 (390)	total: 44.7s	remaining: 1m 6s
bestTest = 0.6752198791
bestIteration = 422
Shrink model to first 423 iterations.
===============================================
test_size : 0.4
random_state : 40
threshold 적용 전 f1 score : 0.6752198791489522
threshold 적용 후 f1 score : 0.7055720074812967
===============================================

 80%|████████  | 4/5 [05:35<01:26, 86.07s/it]

Learning rate set to 0.043835
0:	learn: 0.6172559	test: 0.6202459	best: 0.6202459 (0)	total: 170ms	remaining: 2m 50s
100:	learn: 0.6440253	test: 0.6592975	best: 0.6592975 (100)	total: 11.3s	remaining: 1m 40s
200:	learn: 0.6540122	test: 0.6723137	best: 0.6723137 (200)	total: 22.5s	remaining: 1m 29s
300:	learn: 0.6600988	test: 0.6745268	best: 0.6748687 (299)	total: 33.7s	remaining: 1m 18s
400:	learn: 0.6639892	test: 0.6752576	best: 0.6757856 (375)	total: 44.6s	remaining: 1m 6s
500:	learn: 0.6662971	test: 0.6760340	best: 0.6763038 (491)	total: 55.6s	remaining: 55.4s
600:	learn: 0.6687993	test: 0.6761833	best: 0.6765266 (562)	total: 1m 6s	remaining: 43.9s
bestTest = 0.6765266318
bestIteration = 562
Shrink model to first 563 iterations.
===============================================
test_size : 0.4
random_state : 50
threshold 적용 전 f1 score : 0.676526631835268
threshold 적용 후 f1 score : 0.707950180421371
===============================================

100%|██████████| 5/5 [07:24<00:00, 88.88s/it]
  0%|          | 0/5 [00:00<?, ?it/s]

Learning rate set to 0.04452
0:	learn: 0.6328216	test: 0.6355505	best: 0.6355505 (0)	total: 149ms	remaining: 2m 28s
100:	learn: 0.6444950	test: 0.6563305	best: 0.6563305 (100)	total: 9.59s	remaining: 1m 25s
200:	learn: 0.6532334	test: 0.6655559	best: 0.6655559 (200)	total: 18.9s	remaining: 1m 15s
300:	learn: 0.6580852	test: 0.6668204	best: 0.6674475 (284)	total: 28.4s	remaining: 1m 5s
400:	learn: 0.6628387	test: 0.6684294	best: 0.6685849 (382)	total: 37.8s	remaining: 56.5s
500:	learn: 0.6657964	test: 0.6691992	best: 0.6691992 (500)	total: 47.2s	remaining: 47s
bestTest = 0.6695085886
bestIteration = 522
Shrink model to first 523 iterations.
===============================================
test_size : 0.5
random_state : 10
threshold 적용 전 f1 score : 0.6695085885671004
threshold 적용 후 f1 score : 0.705018905222862
===============================================

 20%|██        | 1/5 [01:36<06:25, 96.36s/it]

Learning rate set to 0.04452
0:	learn: 0.6320051	test: 0.6381475	best: 0.6381475 (0)	total: 169ms	remaining: 2m 48s
100:	learn: 0.6452640	test: 0.6588937	best: 0.6588937 (100)	total: 9.77s	remaining: 1m 26s
200:	learn: 0.6533886	test: 0.6695585	best: 0.6695585 (200)	total: 19.4s	remaining: 1m 16s
300:	learn: 0.6585428	test: 0.6708584	best: 0.6713479 (267)	total: 29s	remaining: 1m 7s
bestTest = 0.6713478847
bestIteration = 267
Shrink model to first 268 iterations.

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:34: RuntimeWarning: invalid value encountered in true_divide

===============================================
test_size : 0.5
random_state : 20
threshold 적용 전 f1 score : 0.6713478846792769
threshold 적용 후 f1 score : 0.0
===============================================

 40%|████      | 2/5 [02:45<04:01, 80.35s/it]

Learning rate set to 0.04452
0:	learn: 0.6173145	test: 0.6227003	best: 0.6227003 (0)	total: 152ms	remaining: 2m 31s
100:	learn: 0.6440766	test: 0.6572201	best: 0.6572201 (100)	total: 9.71s	remaining: 1m 26s
200:	learn: 0.6528879	test: 0.6699617	best: 0.6699617 (200)	total: 19.2s	remaining: 1m 16s
300:	learn: 0.6579479	test: 0.6711206	best: 0.6715202 (270)	total: 28.9s	remaining: 1m 7s
400:	learn: 0.6618350	test: 0.6720984	best: 0.6722234 (393)	total: 38.2s	remaining: 57.1s
500:	learn: 0.6652846	test: 0.6720979	best: 0.6722335 (428)	total: 47.5s	remaining: 47.3s
bestTest = 0.6722335385
bestIteration = 428
Shrink model to first 429 iterations.
===============================================
test_size : 0.5
random_state : 30
threshold 적용 전 f1 score : 0.6722335385273297
threshold 적용 후 f1 score : 0.7029047868492603
===============================================

 60%|██████    | 3/5 [04:11<02:45, 82.74s/it]

Learning rate set to 0.04452
0:	learn: 0.6108401	test: 0.6122576	best: 0.6122576 (0)	total: 148ms	remaining: 2m 27s
100:	learn: 0.6429592	test: 0.6565447	best: 0.6565447 (100)	total: 9.67s	remaining: 1m 26s
200:	learn: 0.6522812	test: 0.6654026	best: 0.6654026 (200)	total: 19.1s	remaining: 1m 15s
300:	learn: 0.6575434	test: 0.6686355	best: 0.6687842 (296)	total: 28.6s	remaining: 1m 6s
400:	learn: 0.6617227	test: 0.6699258	best: 0.6702560 (393)	total: 37.9s	remaining: 56.6s
500:	learn: 0.6647213	test: 0.6703586	best: 0.6703736 (464)	total: 47.1s	remaining: 46.9s
bestTest = 0.6703736317
bestIteration = 464
Shrink model to first 465 iterations.
===============================================
test_size : 0.5
random_state : 40
threshold 적용 전 f1 score : 0.6703736317123901
threshold 적용 후 f1 score : 0.7043534967535433
===============================================

 80%|████████  | 4/5 [05:40<01:25, 85.27s/it]

Learning rate set to 0.04452
0:	learn: 0.6355353	test: 0.6390227	best: 0.6390227 (0)	total: 150ms	remaining: 2m 29s
100:	learn: 0.6458144	test: 0.6600808	best: 0.6600808 (100)	total: 9.66s	remaining: 1m 25s
200:	learn: 0.6541194	test: 0.6684493	best: 0.6684493 (200)	total: 18.9s	remaining: 1m 15s
300:	learn: 0.6584461	test: 0.6707237	best: 0.6707682 (299)	total: 28.5s	remaining: 1m 6s
400:	learn: 0.6624548	test: 0.6710414	best: 0.6713576 (333)	total: 37.9s	remaining: 56.6s
500:	learn: 0.6644628	test: 0.6711945	best: 0.6715174 (448)	total: 47s	remaining: 46.8s
bestTest = 0.6715174125
bestIteration = 448
Shrink model to first 449 iterations.
===============================================
test_size : 0.5
random_state : 50
threshold 적용 전 f1 score : 0.6715174124656865
threshold 적용 후 f1 score : 0.7040870604579561
===============================================

100%|██████████| 5/5 [07:08<00:00, 85.73s/it]

## 결과 종합

In [34]:
all_score_df

         10        20        30        40        50
0  0.686169  0.684951  0.685376  0.684008  0.684365
1  0.715394  0.716773  0.713986  0.712423  0.713624
0  0.682093  0.683339  0.685463  0.680380  0.679918
1  0.711642  0.711525  0.712575  0.714002  0.709949
0  0.676592  0.679545  0.680247  0.679865  0.678811
1  0.709248  0.707529  0.707989  0.705970  0.710570
0  0.671439  0.674141  0.675320  0.675220  0.676527
1  0.703690  0.705403  0.704512  0.705572  0.707950
0  0.669509  0.671348  0.672234  0.670374  0.671517
1  0.705019  0.000000  0.702905  0.704353  0.704087

In [37]:
mod_all_score_df = all_score_df.copy()

In [39]:
mod_all_score_df.index= [['0.1','0.1','0.2','0.2','0.3','0.3','0.4','0.4','0.5','0.5'],
                        ['0','1','0','1','0','1','0','1','0','1']]

In [40]:
mod_all_score_df

             10        20        30        40        50
0.1 0  0.686169  0.684951  0.685376  0.684008  0.684365
    1  0.715394  0.716773  0.713986  0.712423  0.713624
0.2 0  0.682093  0.683339  0.685463  0.680380  0.679918
    1  0.711642  0.711525  0.712575  0.714002  0.709949
0.3 0  0.676592  0.679545  0.680247  0.679865  0.678811
    1  0.709248  0.707529  0.707989  0.705970  0.710570
0.4 0  0.671439  0.674141  0.675320  0.675220  0.676527
    1  0.703690  0.705403  0.704512  0.705572  0.707950
0.5 0  0.669509  0.671348  0.672234  0.670374  0.671517
    1  0.705019  0.000000  0.702905  0.704353  0.704087

In [36]:
all_thr_df

         10        20        30        40        50
0  0.378409  0.377921  0.370538  0.382729  0.396402
0  0.385641  0.379673  0.391394  0.363218  0.375285
0  0.373730  0.384465  0.390848  0.384499  0.379938
0  0.372317  0.384494  0.373631  0.371829  0.362747
0  0.375448  0.893802  0.378210  0.382710  0.379275

### 오류난 특성 제거

In [ ]:
# del_col = ['30', '40', '60', '70']
# pred_proba_df = pred_proba_df.drop(del_col, axis=1)
# thr_df = thr_df.drop(del_col, axis=1)
# score_df = score_df.drop(del_col, axis=1)

In [ ]:
pred_proba_df['mean'] = pred_proba_df.mean(axis=1)
thr_df['mean'] = thr_df.mean(axis=1)
score_df['mean'] = score_df.mean(axis=1)

### threshold 값

In [ ]:
all_thr_df

         10        20        30  ...       90       100      mean
0  0.391287  0.388262  0.373833  ...  0.36671  0.385416  0.378773

[1 rows x 11 columns]

## 자체평가

In [ ]:
all_score_df

                      10        20        30  ...        90       100      mean
threshold 적용 전  0.680541  0.682001  0.680907  ...  0.679578  0.683618  0.680178
threshold 적용 후  0.710426  0.711445  0.709934  ...  0.710721  0.710469  0.710272

[2 rows x 11 columns]

## test 예측

In [ ]:
pred = pred_proba_df['mean'].tolist() >= thr_df['mean'].values
pred = pred.astype(int)
pred

array([1, 0, 1, ..., 1, 1, 1])

In [ ]:
np.unique(pred, return_counts=True)

(array([0, 1]), array([10268, 36136]))

# 제출파일 불러오기

In [ ]:
# sub = pd.read_csv('../data/sample_submission.csv')
sub = pd.read_csv('/content/drive/MyDrive/GitHub/Dacon/TP2(잡케어)/data/sample_submission.csv')
sub.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46404 entries, 0 to 46403
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      46404 non-null  int64
 1   target  46404 non-null  int64
dtypes: int64(2)
memory usage: 725.2 KB

# 제출파일 생성

In [ ]:
sub['target'] = pred
sub['target'].value_counts()

1    36136
0    10268
Name: target, dtype: int64

In [ ]:
file_ver = '5.5'
# sub.to_csv(f'sub_ver{file_ver}.csv', index=False)
sub.to_csv(f'/content/drive/MyDrive/GitHub/Dacon/TP2(잡케어)/03_모델선정및개선/sub_ver{file_ver}.csv', index=False)

# 코드 마지막